### ISSUE TITLE
exec /usr/local/bin/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by BenRoe** [lanrat/hass-screenshot#9]
If i start the docker-compose i get the following error in the logs.

```bash
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

This is my docker compose

```yaml
  hass-screenshot:
    container_name: hass-screenshot
    image: lanrat/hass-screenshot
    depends_on:
      - homeassistant
    deploy:
      resources:
        limits:
          memory: 200MB
    environment:
      - TZ=Europe/Berlin
      - HA_BASE_URL=http://192.168.1.1:8123
      - HA_ACCESS_TOKEN=${HASS_TOKEN_DASHBOARD_TO_PNG}
      - LANGUAGE=en
      # - MQTT_SERVER=MQTT_SERVER_IP
      - REAL_TIME=true
      - RENDERING_DELAY=2
      - COLOR_MODE=GrayScale
        # image 1
      - HA_SCREENSHOT_URL=/lovelace/homeplate?kiosk
      - RENDERING_SCREEN_HEIGHT=825
      - RENDERING_SCREEN_WIDTH=1200
      - GRAYSCALE_DEPTH=3
        # image 2
      # - HA_SCREENSHOT_URL_2=/lovelace-infra/hud2?kiosk
      # - RENDERING_SCREEN_HEIGHT_2=800
      # - RENDERING_SCREEN_WIDTH_2=600
      # - GRAYSCALE_DEPTH_2=4
        # image 3
      # - HA_SCREENSHOT_URL_3=/lovelace-infra/hud3?kiosk
      # - RENDERING_SCREEN_HEIGHT_3=800
      # - RENDERING_SCREEN_WIDTH_3=600
      # - GRAYSCALE_DEPTH_3=4
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - "/DATA/AppData/hass-lovelace-kindle-screensaver:/output"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1"
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 60s
```

**Comment by lanrat** [comment]
Are you still having this issue?

Did you build the docker image for the same CPU architecture for the machine that is running it?

**Comment by BenRoe** [comment]
Still get the error.
What do you mean with build? I added the code above to my docker-compose.yaml and started it with Portainer.
It's a Raspberry Pi 4

**Comment by lanrat** [comment]
The raspberry pi has an arm CPU. The pre&built image I provide is only for x86_64 CPUs.

In order to run this on a pi, you will need to build the image yourself on the pi.

**Comment by BenRoe** [comment]
You use `setup-buildx-action` to build the docker image.
You could use
```yaml
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
 ```
 to build the images for multiple platforms.

https://github.com/docker/setup-buildx-action#usage

Right now i do not have the time to get into it and open a PR.
